### ISSUE TITLE
Create design report

### ISSUE THREAD

**Issue by solvip** [hundarogborn/TicTacToe#14]
"Document describing the initial design"

Maybe we can clarify what they want?

**Comment by sveinng** [comment]
https://piazza.com/class/irxol0x43t6pr?cid=119

Þetta á að vera stutt skýrsla þar sem þetta er lítið forrit. 
Þetta er hönnunaskýrsla ekki kröfugreining (requirement analysis).
Og við leggjum áherslu á upphafleg hönnun þar ekki nauðsynlega að endurspegla hvernig lokaafurðin er. Við viljum bara að þið setjið niður einhvern ramma áður en þið byrjið að forrita á fullu. Hún gæti t.d. innihaldið klasarit eða yfirlit yfir lagskiptingu í kerfinu ef það er til staðar. 
Þetta getur verið einblöðungur en þarf að gefa okkur hugmynd um hönnunina, þið notið eitthvað af þeim tólum sem þið lærðuð í Greiningu og Hönnun.

**Comment by rebekka123** [comment]
[ProblemSolvingProject3.pdf](https://github.com/hundarogborn/TicTacToe/files/545506/ProblemSolvingProject3.pdf)

Þetta er klasaritið sem Hannes bjó til sem lausn við einu verkefninu í Greiningu og Hönnun

**Comment by sveinng** [comment]
Jebb - þetta er akkúrat það sem við þurfum að gera.
Ég er búinn að skella í initial riss fyrir klasarit. Endilega ræða og bæta :)

https://github.com/hundarogborn/TicTacToe/wiki/Design-Report

**Comment by solvip** [comment]
Ég bjó til PR #26 sem útfærir e-a documentation

**Comment by solvip** [comment]
Marking this done
