### ISSUE TITLE
Travis-CI uploads release artifacts to GitHub 

### ISSUE THREAD

**Issue by solvip** [hundarogborn/TicTacToe#6]
https://docs.travis-ci.com/user/deployment/releases/

**Comment by sveinng** [comment]
Do we still want this?

**Comment by solvip** [comment]
I don't know.  In real life, I'd like to be able to access the history of releases.  For example, how do we want to roll back when we deploy broken things?

**Comment by sveinng** [comment]
Makes sense, do you know how to do it?

**Comment by solvip** [comment]
Resolved in #30
